steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files: hooks/**

  - label: ":sparkles:"
    plugins:
      plugin-linter#v2.0.0:
        id: habitat

  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v3.0.3:
        run: tests

  - wait
  - label: run the plugin
    plugins:
      ${BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        origin: test-origin
        channel: test-channel
        auth-token: test-auth-token
