steps:
  - label: "Plugin shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files: hooks/**

  - label: "Plugin lint"
    plugins:
      plugin-linter#v2.0.0:
        id: habitat

  - label: "Plugin test"
    plugins:
      docker-compose#v3.0.3:
        run: tests

  - wait
  - label: "Plugin functional test"
    plugins:
      ${BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        origin: gscho
        plan-path: fixtures
        upload: false
